name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.1" # Use the appropriate Flutter version
      - run: npm install -g firebase-tools
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KARTHIK_WEB }}
          channelId: live
          projectId: karthik-web
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks  # 👈 Add this 
